name: Build master

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Build & Deploy
        shell: bash
        run: |
          mvn deploy --batch-mode -DdeployAtEnd=true -X
        env:
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}