name: Build master

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build & Deploy
        shell: bash
        run: |
          mvn --batch-mode deploy
          echo "Deployed artifacts"
        env:
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}