name: Build master

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build & Deploy
        shell: bash
        run: |
          mvn versions:set -DnewVersion=${GITHUB_SHA::8} --batch-mode
          mvn deploy --batch-mode -DdeployAtEnd=true -PpublishGithub -Dmaven.wagon.http.pool=false
          echo "Deployed artifacts"
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}