name: Deploy new package

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Create tag
        uses: paulhatch/semantic-version@v5.4.0
        id: create-tag
        with:
          tag_prefix: ""
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          bump_each_commit: true
      - name: Build and deploy
        shell: bash
        run: |
          echo "Setting tag ${{ steps.create-tag.outputs.version }}"
          mvn versions:set -DnewVersion="${{ steps.create-tag.outputs.version }}"
          mvn deploy --batch-mode --settings ./settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}