name: Build master

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Build & Deploy
        shell: bash
        run: |
          mvn versions:set -DnewVersion=${GITHUB_SHA::8} --batch-mode
          mvn deploy --batch-mode -DdeployAtEnd=true
#          mvn deploy -X source:jar-no-fork deploy -DskipTests=true -Dmaven.wagon.http.pool=false  --batch-mode -DdeployAtEnd=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}