name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
      - name: Build
        shell: bash
        run: mvn verify --batch-mode --settings ./settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update release draft
        uses: release-drafter/release-drafter@c2e2804cc59f45f57076a99af580d0fedb697927 # 7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
